// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://solybuwclcmdiqplilsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvbHlidXdjbGNtZGlxcGxpbHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMzE1MDIsImV4cCI6MjA2NTYwNzUwMn0.VUaempIlDcixeJRpY2-2BsY7-CytZ5Yqzb6uEdtZ1yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);